
- replace:
    path: '{{ home }}/{{ relative_repository_path }}/tools/commons/commons.conf'
    regexp: '^sendingInterval = .*$'
    replace: 'sendingInterval = {{ interval }}'
  when: interval is defined
