- name: Run validator.
  shell: java -jar -Dlog4j.configuration=validator.log4j.properties tools/validator/target/scala-2.11/Validator-assembly-0.1.0-SNAPSHOT.jar
  args:
    chdir: "~/{{ relative_repository_path }}"
