---

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "Set Topic Prefix."
      include: ../roles/benchmark/tasks/set_topic_prefix.yml home=~ prefix="{{ topic_prefix }}"
      when: topic_prefix is defined
    - name: "Set Benchmark Run."
      include: ../roles/benchmark/tasks/set_benchmark_run.yml home=~ run="{{ benchmark_run }}"
      when: benchmark_run is defined
    - name: "Set Sending Interval"
      include: ../roles/benchmark/tasks/set_sending_interval.yml home=~ interval="{{ sending_interval }}"
      when: sending_interval is defined
    - name: "Set Scale Factor"
      include: ../roles/benchmark/tasks/set_scale_factor.yml home=~ sf="{{ scale_factor }}"
      when: scale_factor is defined

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "Compile Project"
      include: ../roles/benchmark/tasks/compile.yml home=~
    - name: "Create Kafka Topics"
      include: ../roles/kafka-topic/tasks/create.yml
    - name: "Reassign Kafka Topics"
      include: ../roles/kafka-topic/tasks/reassign.yml
    - name: "Reassign Verify Kafka Topics"
      include: ../roles/kafka-topic/tasks/reassignVerify.yml

- hosts: master
  tasks:
    - name: "Copy Config File"
      include: ../roles/benchmark/tasks/copy_config.yml
    - name: "Compile Project"
      include: ../roles/benchmark/tasks/compile.yml home={{ benchmarker_home }}
      become: yes
      become_user: benchmarker
    - name: "Terminate Running Jobs"
      include: ../roles/flink/tasks/terminate_running_jobs.yml
    - name: "Start Jobs"
      include: ../roles/flink/tasks/start_jobs.yml
    - name: "Waiting a few seconds for streaming jobs to start."
      pause:
        seconds: 30

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "Start Datasender"
      include: ../roles/benchmark/tasks/start_datasender.yml
    - name: "Waiting a few seconds for streaming system to finish queries."
      pause:
        seconds: 30
    - name: "Start Validator"
      include: ../roles/benchmark/tasks/start_validator.yml

- hosts: master
  tasks:
    - name: "Terminate Running Jobs"
      include: ../roles/flink/tasks/terminate_running_jobs.yml
